CREATE TABLE USERS (
    EMAIL VARCHAR(200) PRIMARY KEY,
    ID BLOB,
    CHALLENGE BLOB,
    CREDENTIAL_ID VARCHAR(200)
);

CREATE TABLE CREDENTIALS (
    CREDENTIAL_ID VARCHAR(200) PRIMARY KEY,
    ATTESTED_CREDENTIAL_DATA BLOB,
    ENVELOPE BLOB,
    TRANSPORTS VARCHAR(200),
    AUTHENTICATOR_EXTENSIONS BLOB,
    CLIENT_EXTENSIONS VARCHAR(200),
    COUNTER BIGINT
);