CREATE TABLE IF NOT EXISTS USERS (
    EMAIL VARCHAR(200) NOT NULL PRIMARY KEY,
    ID BLOB,
    CHALLENGE BLOB,
    CREDENTIAL_ID VARCHAR(256)
);

CREATE TABLE IF NOT EXISTS CREDENTIALS (
    CREDENTIAL_ID VARCHAR(256) NOT NULL PRIMARY KEY,
    ATTESTED_CREDENTIAL_DATA BLOB,
    ENVELOPE BLOB,
    TRANSPORTS VARCHAR(200),
    AUTHENTICATOR_EXTENSIONS BLOB,
    CLIENT_EXTENSIONS VARCHAR(200),
    COUNTER BIGINT
);